# Generated by Django 4.2.11 on 2024-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
        migrations.AddField(
            model_name='trade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
