# Generated by Django 4.2.11 on 2024-05-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_promo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discount',
        ),
    ]
